### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by josephajibodu** [FLIP-Digital-Technologies/Cardvest-v2#54]
Would appreciate updating the readme to just contain what is necessary about the project.

Some of the sections in this current Readme are perfect, you can leave them. 

Here's a guide on whats expected:

**Installation** 📥 - this should instead be tailored to how another developer can run this project on their own computer.

> You can leave the following sections: `Rename project and bundles 📝 📦`, `Environment Setup 🌐`, and `Scripts 🔧` section.

Then include the necessary fastlane commands.  This would go a long way in helping anyone set up the project.

Thanks.

@Oluwashina  please check if I omitted anything that should be included.

**Comment by Oluwashina** [comment]
@BigUncleYemi Please check that your readme contains necessary information about how any developer can run or start or set up the project on his end.
